-------------------------------------------------------------------------------
-- Dice Master (C) 2023 <The League of Lordaeron> - Moon Guard
-------------------------------------------------------------------------------
--

--
-- The roll options list
-- name			Name of the roll option
-- subName		Pattern for subbing text in description tooltips
-- wheelName	Name to display on the Roll Wheel
-- desc			Description of the roll option
-- skill		Skill used as a modifier
--

DiceMaster4.RollList = {
	["Combat Actions"] = {
		{
			name = "Melee Attack",
			subName = "Melee Attack[s]?",
			wheelName = "Melee|nAttack",
			iconID = 40,
			desc = "An attempt to strike an enemy with a melee weapon.", 
			skill = "Strength",
		},
		{
			name = "Ranged Attack",
			subName = "Ranged Attack[s]?",
			wheelName = "Ranged|nAttack",
			iconID = 41,
			desc = "An attempt to strike an enemy with a ranged weapon.", 
			skill = "Dexterity",
		},
		{
			name = "Spell Attack",
			subName = "Spell Attack[s]?",
			wheelName = "Spell|nAttack",
			iconID = 42,
			desc = "An attempt to cast a harmful spell against an enemy.", 
			skill = "Intelligence",
		},
		{
			name = "Defence",
			subName = "Defen[cs]e[s]?",
			iconID = 43,
			desc = "An attempt to defend yourself from enemy damage.",
			skill = "Constitution",
		},
		{
			name = "Spell Defence",
			subName = "Spell Defen[cs]e[s]?",
			iconID = 44,
			desc = "An attempt to defend yourself from enemy spell damage.",
			skill = "Intelligence",
		},
	},
	["Skills"] = {
		{
			name = "Acrobatics",
			subName = "Acrobatics",
			wheelName = "Acrob.",
			iconID = 52,
			desc = "An attempt to dive, flip, jump, and An attempt to avoid attacks and overcome obstacles.", 
			skill = "Dexterity",
		},
		{
			name = "Arcana",
			subName = "Arcana",
			iconID = 63,
			desc = "An attempt to recall lore about spells and magic items.", 
			skill = "Intelligence",
		},
		{
			name = "Athletics",
			subName = "Athletics",
			wheelName = "Athle.",
			iconID = 51,
			desc = "An attempt to swim, climb, flee, fly, or outrun someone.", 
			skill = "Strength",
		},
		{
			name = "Bluff",
			subName = "Bluff",
			iconID = 4,
			desc = "An attempt to deceive, trick, or lie to someone.", 
			skill = "Charisma",
		},
		{
			name = "Diplomacy",
			subName = "Diplomacy",
			wheelName = "Diplom.",
			iconID = 0,
			desc = "An attempt to persuade or win favour with someone.", 
			skill = "Charisma",
		},
		{
			name = "Disable Device",
			subName = "Disable Device",
			wheelName = "Disable|nDevice",
			iconID = 2,
			desc = "An attempt to disarm a trap or disable a lock.", 
			skill = "Dexterity",
		},
		{
			name = "Disguise",
			subName = "Disguise",
			iconID = 27,
			desc = "An attempt to change your appearance.", 
			skill = "Charisma",
		},
		{
			name = "Escape",
			subName = "Escape",
			wheelName = "Escape",
			iconID = 25,
			desc = "An attempt to slip bonds and escape from grapples.", 
			skill = "Dexterity",
		},
		{
			name = "Grapple",
			subName = "Grapple[s]?",
			iconID = 10,
			desc = "An attempt to disarm or disable an enemy, or reverse grapples.", 
			skill = "Strength",
		},
		{
			name = "Healing",
			subName = "Heal[ingsed]*",
			wheelName = "Heal",
			iconID = 53,
			desc = "An attempt to mend wounds or restore health to someone.", 
			skill = "Wisdom",
		},
		{
			name = "Insight",
			subName = "Insight",
			wheelName = "Sense|nMotive",
			iconID = 20,
			desc = "An attempt to discern intent or decipher body language.", 
			skill = "Wisdom",
		},
		{
			name = "Intimidation",
			subName = "Intimidation",
			wheelName = "Intimidate",
			iconID = 54,
			desc = "An attempt to taunt, coerce, or frighten someone.", 
			skill = "Charisma",
		},
		{
			name = "Knowledge",
			subName = "Knowledge",
			iconID = 8,
			desc = "An attempt to determine your education or understanding of a particular topic.", 
			skill = "Intelligence",
		},
		{
			name = "Perception",
			subName = "Perception",
			wheelName = "Percep.",
			iconID = 7,
			desc = "An attempt to notice fine details and alert yourself to danger.", 
			skill = "Wisdom",
		},
		{
			name = "Performance",
			subName = "Performance[s]?",
			wheelName = "Perform",
			iconID = 13,
			desc = "An attempt to impress an audience with your talent and skill.", 
			skill = "Charisma",
		},
		{
			name = "Spellcraft",
			subName = "Spellcraft",
			iconID = 21,
			desc = "An attempt to cast or use spells and magic items.", 
			skill = "Intelligence",
		},
		{
			name = "Stealth",
			subName = "Stealth",
			wheelName = "Sneak",
			iconID = 55,
			desc = "An attempt to avoid detection and remain unseen.", 
			skill = "Dexterity",
		},
		{
			name = "Survival",
			subName = "Survival",
			wheelName = "Survive",
			iconID = 23,
			desc = "An attempt to survive or navigate in the wilderness.", 
			skill = "Wisdom",
		},
	},
	["Saving Throws"] = {
		{
			name = "Fortitude Save",
			subName = "Fortitude Save[s]?",
			wheelName = "Fort.|nSave",
			iconID = 56,
			desc = "An attempt to resist physical punishment or pain.", 
			skill = "Constitution",
		},
		{
			name = "Reflex Save",
			subName = "Reflex Save[s]?",
			wheelName = "Reflex|nSave",
			iconID = 58,
			desc = "An attempt to avoid or prevent an unexpected action.", 
			skill = "Dexterity",
		},
		{
			name = "Will Save",
			subName = "Will Save[s]?",
			wheelName = "Will|nSave",
			iconID = 57,
			desc = "An attempt to resist mental influence.", 
			skill = "Wisdom",
		},
	},
}

DiceMaster4.AttributeList = {
	["Strength"] = {
		desc = "A measure of your muscle and physical power.",
	},
	["Dexterity"] = {
		desc = "A measure of your hand-eye coordination, agility, reflexes, and balance.",
	},
	["Constitution"] = {
		desc = "A measure of your health and stamina.",
	},
	["Intelligence"] = {
		desc = "A measure of how well you learn and reason.",
	},
	["Wisdom"] = {
		desc = "A measure of your willpower, common sense, awareness, and intuition.",
	},
	["Charisma"] = {
		desc = "A measure of your personality, personal magnetism, ability to lead, and appearance.",
	},
}

DiceMaster4.TermsList = {
	["Effects"] = {
		{
			name = "Advantage",
			subName = "Advantage",
			iconID = 38,
			desc = "Allows a character to roll the same dice twice, and take the greater of the two resulting numbers.",
		},
		{
			name = "Armour Penetration",
			subName = "Arm[ou]*r Penetration",
			iconID = 16,
			desc = "Allows a character's successful attack to bypass the target's Armour this turn.",
		},
		{
			name = "Cleave",
			subName = "Cleave[s]*",
			iconID = 30,
			desc = "Allows a character's successful attack to inflict damage to up to two additional targets.",
		},
		{
			name = "Control",
			subName = "Control[sleding]*",
			iconID = 47,
			desc = "Allows a character to take command of a target and control their actions until the effect ends.",
		},
		{
			name = "Counter",
			subName = "Counter[seding]*",
			iconID = 48,
			desc = "Allows a character to immediately attack the same target after a successful Defence roll.",
		},
		{
			name = "Disadvantage",
			subName = "Disadvantage",
			iconID = 39,
			desc = "Allows a character to roll the same dice twice, and take the lesser of the two resulting numbers.",
		},
		{
			name = "Disarm",
			subName = "Disarm[s]*",
			iconID = 31,
			desc = "Removes a target's weapons for one turn, preventing them from using them.",
		},
		{
			name = "Dispel",
			subName = "Dispel[sleding]*",
			iconID = 61,
			desc = "Removes a buff or debuff from a creature.",
		},
		{
			name = "Double or Nothing",
			subName = "Double or Nothing",
			iconID = 32,
			desc = "An unmodified D40 roll. If the roll succeeds, the character is rewarded with a critical success; however, if the roll fails, the character suffers a critical failure.",
		},
		{
			name = "Empower",
			subName = "Empower[seding]*",
			iconID = 45,
			desc = "Allows a character's successful Melee Attack or Ranged Attack to be considered a Spell Attack.",
		},
		{
			name = "Immunity",
			subName = "Immunity",
			iconID = 46,
			desc = "Prevents a character from suffering any damage from a failure this turn.",
		},
		{
			name = "Intercept",
			subName = "Intercept[edsing]*",
			iconID = 49,
			desc = "Intercepts another character's failure, taking the full amount of damage.",
		},
		{
			name = "Leech",
			subName = "Leech[edsing]*",
			iconID = 62,
			desc = "Causes damage inflicted by a character to also restore an equal amount of their health.",
		},
		{
			name = "Multistrike",
			subName = "Multistrike",
			iconID = 28,
			desc = "Allows a character to attack twice on their turn; however, their second attack only inflicts 1 damage (2 if critically successful).",
		},
		{
			name = "Natural 1",
			subName = "NAT1",
			iconID = 37,
			desc = "A roll of 1 that is achieved before dice modifiers are applied that results in critical failure.",
			altTerm = "NAT1",
		},
		{
			name = "Natural 20",
			subName = "NAT20",
			iconID = 36,
			desc = "A roll of 20 that is achieved before dice modifiers are applied that results in critical success.",
			altTerm = "NAT20",
		},
		{
			name = "Reflect",
			subName = "Reflect[edsing]*",
			iconID = 50,
			desc = "Causes damage intended for a character to reflect back at the attacker.",
		},
		{
			name = "Reload",
			subName = "Reload[edsing]*",
			iconID = 29,
			desc = "Grants the character's active-use trait another use.",
		},
		{
			name = "Revive",
			subName = "Reviv[desing]*",
			iconID = 34,
			desc = "Allows a character with |cFFFFFFFF0|r|TInterface/AddOns/DiceMaster/Texture/health-heart:12|t|cFFffd100 remaining to return to combat with |cFFFFFFFF3|r|TInterface/AddOns/DiceMaster/Texture/health-heart:12|t|cFFffd100.",
		},
		{
			name = "Secret",
			subName = "Secret[s]*",
			iconID = 60,
			desc = "A secret effect that remains hidden until activated by a specific condition.",
		},
		{
			name = "Taunt",
			subName = "Taunt[seding]*",
			iconID = 59,
			desc = "Forces a target to attack the character on its next turn (if permitted).",
		},
	},
	["Conditions"] = {
		{
			name = "Blind",
			altName = "Blind",
			subName = "Blind[seding]*",
			icon = "Interface/Icons/ability_cheapshot",
			iconID = 1,
			desc = "The target is unable to see and automatically fails any ability check that requires sight. Attack rolls against the target have Advantage, and the target's attack rolls have Disadvantage.",
			animation = 77,
		},
		{
			name = "Charm",
			altName = "Charmed",
			subName = "Charm[seding]*",
			icon = "Interface/Icons/spell_shadow_seduction",
			iconID = 3,
			desc = "The target is entranced and unable to attack the charmer. The charmer has Advantage on any ability check to interact socially with the target.",
			effect = 63837,
			animation = 83,
		},
		{
			name = "Deafen",
			altName = "Deaf",
			subName = "Deafen[seding]*",
			icon = "Interface/Icons/inv_misc_ear_human_01",
			iconID = 5,
			desc = "The target is unable to hear and automatically fails any ability check that requires hearing.",
		},
		{
			name = "Fatigue",
			altName = "Fatigued",
			subName = "Fatigu[esding]*",
			icon = "Interface/Icons/spell_shadow_mindsteal",
			iconID = 6,
			desc = "The target cannot run nor charge. The target has Disadvantage on Fortitude and Reflex Saves.",
			animation = 1154,
		},
		{
			name = "Frighten",
			altName = "Frightened",
			subName = "Frighten[seding]*",
			icon = "Interface/Icons/spell_shadow_possession",
			iconID = 9,
			desc = "The target has Disadvantage on ability checks and attack rolls while the source of its fear is within line of sight. The target cannot willingly move closer to the source of its fear.",
			effect = 123888,
			animation = 225,
		},
		{
			name = "Grapple",
			altName = "Grappled",
			subName = "Grappl[edsing]*",
			icon = "Interface/Icons/spell_nature_shamanrage",
			iconID = 10,
			desc = "The target is unable to move for the duration of the Grapple. The condition ends if the grappler is incapacitated.",
			animation = 14,
		},
		{
			name = "Incapacitate",
			altName = "Incapacitated",
			subName = "Incapacitat[esding]*",
			icon = "Interface/Icons/spell_nature_sleep",
			iconID = 11,
			desc = "The target cannot take actions or reactions.",
			animation = 14,
		},
		{
			name = "Invisible",
			altName = "Invisible",
			subName = "Invisib[ilitye]*",
			icon = "Interface/Icons/spell_nature_invisibilty",
			iconID = 12,
			desc = "The target is impossible to see without the aid of magic or a special sense. Attack rolls against the target have Disadvantage, and the target's attack rolls have Advantage.",
			effect = 118726,
		},
		{
			name = "Paralyse",
			altName = "Paralysed",
			subName = "Paraly[sz]*[esding]*",
			icon = "Interface/Icons/spell_nature_wispsplodegreen",
			iconID = 14,
			desc = "The target cannot take actions or reactions, move, or speak. The target automatically fails Fortitude and Reflex Saves. Attack rolls against the target have Advantage.",
			animation = 14,
		},
		{
			name = "Petrify",
			altName = "Petrified",
			subName = "Petrif[iyesding]*",
			icon = "Interface/Icons/ability_golemthunderclap",
			iconID = 15,
			desc = "The target is transformed into solid stone and cannot take actions or reactions, move, or speak. Attack rolls against the target have Advantage. The target is immune to poison and disease, but automatically fails Fortitude and Reflex Saves.",
		},
		{
			name = "Poison",
			altName = "Poisoned",
			subName = "Poison[seding]*",
			icon = "Interface/Icons/spell_nature_nullifydisease",
			iconID = 18,
			desc = "The target has Disadvantage on attack rolls and ability checks.",
			effect = 108139,
			animation = 8,
		},
		{
			name = "Prone",
			altName = "Prone",
			subName = "Prone",
			icon = "Interface/Icons/ability_rogue_feigndeath",
			iconID = 19,
			desc = "The target's only movement option is to crawl, unless it stands up and ends the condition. The target has Disadvantage on attack rolls. Melee Attack rolls against the target have Advantage, but Ranged Attack rolls have Disadvantage.",
			animation = 121,
		},
		{
			name = "Restrain",
			altName = "Restrained",
			subName = "Restrain[seding]*",
			icon = "Interface/Icons/inv_misc_net_01",
			iconID = 22,
			desc = "The target is unable to move and has Disadvantage on Reflex Saves. Attack rolls against the target have Advantage, and the target's attack rolls have Disadvantage.",
			effect = 14468,
			animation = 1316,
		},
		{
			name = "Silence",
			altName = "Silenced",
			subName = "Silenc[esding]*",
			icon = "Interface/Icons/spell_holy_silence",
			iconID = 33,
			desc = "Interrupts a target's spellcast and prevents them from casting spells on their next turn.",
			animation = 8,
		},
		{
			name = "Slow",
			altName = "Slowed",
			subName = "Slow[seding]*",
			icon = "Interface/Icons/spell_nature_slow",
			iconID = 35,
			desc = "Reduces a target's movement speed until the effect ends.",
			animation = 1160,
		},
		{
			name = "Stun",
			altName = "Stunned",
			subName = "Stun[sneding]*",
			icon = "Interface/Icons/spell_frost_stun",
			iconID = 24,
			desc = "The target cannot take actions or reactions, cannot move, and can speak only falteringly. The target automatically fails Fortitude and Reflex Saves. Attack rolls against the target have Advantage.",
			effect = 14482,
			animation = 14,
		},
		{
			name = "Unconscious",
			altName = "Unconscious",
			subName = "Unconscious",
			icon = "Interface/Icons/spell_nature_sleep",
			iconID = 26,
			desc = "The target cannot take actions or reactions, cannot move or speak, and drops whatever it is holding. The target automatically fails Fortitude and Reflex Saves and attack rolls against the target have Advantage.",
			effect = 91304,
			animation = 100,
		},
	},
	["Other"] = {
		{
			name = "Armour",
			subName = "Armo[u]*r",
			desc = "Extends a character's Health beyond the maximum amount by a certain value. Damage taken will usually be deducted from Armour before Health unless otherwise specified.",
			altTerm = "AR",
		},
		{
			name = "Health",
			subName = "Health",
			desc = "A measure of a character's health or an object's integrity. Damage taken decreases Health, and healing restores Health.",
			altTerm = "HP",
		},
	},
}