DiceMaster4.textureList = {
	[ "Mage" ] = {
		{ file = "Arcane Missiles", id = 449486, orientation = "VERTICAL" },
		{ file = "Arcane Missiles 1", id = 1027131, orientation = "VERTICAL" },
		{ file = "Arcane Missiles 2", id = 1027132, orientation = "VERTICAL" },
		{ file = "Arcane Missiles 3", id = 1027133, orientation = "VERTICAL" },
		{ file = "Brain Freeze", id = 449488, orientation = "HORIZONTAL" },
		{ file = "Frozen Fingers", id = 449489, orientation = "VERTICAL" },
		{ file = "Hot Streak", id = 449490, orientation = "VERTICAL" },
		{ file = "Impact", id = 457658, orientation = "HORIZONTAL" },
	},
	[ "Generic" ] = {
		{ file = "Generic Arc 01", id = 450917, orientation = "VERTICAL" },
		{ file = "Generic Arc 02", id = 450918, orientation = "VERTICAL" },
		{ file = "Generic Arc 03", id = 450919, orientation = "VERTICAL" },
		{ file = "Generic Arc 04", id = 450920, orientation = "VERTICAL" },
		{ file = "Generic Arc 05", id = 450921, orientation = "VERTICAL" },
		{ file = "Generic Arc 06", id = 450922, orientation = "VERTICAL" },
		{ file = "Generic Top 01", id = 450923, orientation = "HORIZONTAL" },
		{ file = "Generic Top 02", id = 450924, orientation = "HORIZONTAL" },
	},
	[ "Paladin" ] = {
		{ file = "Art of War", id = 450913, orientation = "VERTICAL" },
		{ file = "Daybreak", id = 459313, orientation = "VERTICAL" },
		{ file = "Denounce", id = 511469, orientation = "HORIZONTAL" },
		{ file = "Grand Crusader", id = 450925, orientation = "VERTICAL" },
		{ file = "Hand of Light", id = 459314, orientation = "HORIZONTAL" },
	},
	[ "Hunter" ] = {
		{ file = "Focus Fire", id = 450916, orientation = "HORIZONTAL" },
		{ file = "Lock and Load", id = 450926, orientation = "HORIZONTAL" },
		{ file = "Master Marksman", id = 450928, orientation = "HORIZONTAL" },
		{ file = "Thrill of the Hunt 1", id = 1029138, orientation = "VERTICAL" },
		{ file = "Thrill of the Hunt 2", id = 1029139, orientation = "VERTICAL" },
		{ file = "Thrill of the Hunt 3", id = 1029140, orientation = "VERTICAL" },
	},
	[ "Shaman" ] = {
		{ file = "Echo of the Elements", id = 1057288, orientation = "VERTICAL" },
		{ file = "Fulmination", id = 467696, orientation = "HORIZONTAL" },
		{ file = "High Tide", id = 2851788, orientation = "HORIZONTAL" },
		{ file = "Maelstrom Weapon", id = 450927, orientation = "HORIZONTAL" },
		{ file = "Maelstrom Weapon 1", id = 1028136, orientation = "HORIZONTAL" },
		{ file = "Maelstrom Weapon 2", id = 1028137, orientation = "HORIZONTAL" },
		{ file = "Maelstrom Weapon 3", id = 1028138, orientation = "HORIZONTAL" },
		{ file = "Maelstrom Weapon 4", id = 1028139, orientation = "HORIZONTAL" },
	},
	[ "Warlock" ] = {
		{ file = "Backlash", id = 460830, orientation = "HORIZONTAL" },
		{ file = "Backlash Green", id = 801266, orientation = "HORIZONTAL" },
		{ file = "Demonic Core", id = 2851787, orientation = "HORIZONTAL" },
		{ file = "Demonic Core Vertical", id = 2888300, orientation = "VERTICAL" },
		{ file = "Imp Empowerment", id = 449491, orientation = "VERTICAL" },
		{ file = "Imp Empowerment Green", id = 801267, orientation = "VERTICAL" },
		{ file = "Molten Core", id = 458741, orientation = "VERTICAL" },
		{ file = "Molten Core Green", id = 801268, orientation = "VERTICAL" },
		{ file = "Nightfall", id = 449492, orientation = "VERTICAL" },
	},
	[ "Monk" ] = {
		{ file = "Dark Tiger", id = 603338, orientation = "VERTICAL" },
		{ file = "Monk Blackout Kick", id = 1001511, orientation = "VERTICAL" },
		{ file = "Monk Ox", id = 623950, orientation = "VERTICAL" },
		{ file = "Monk Ox 2", id = 1028091, orientation = "VERTICAL" },
		{ file = "Monk Ox 3", id = 1028092, orientation = "VERTICAL" },
		{ file = "Monk Serpent", id = 623951, orientation = "VERTICAL" },
		{ file = "Monk Tiger", id = 623952, orientation = "VERTICAL" },
		{ file = "Monk Tiger Palm", id = 1001512, orientation = "VERTICAL" },
		{ file = "White Tiger", id = 603339, orientation = "VERTICAL" },
	},
	[ "Druid" ] = {
		{ file = "Berserk", id = 510822, orientation = "HORIZONTAL" },
		{ file = "Eclipse Moon", id = 450914, orientation = "VERTICAL" },
		{ file = "Eclipse Sun", id = 450915, orientation = "VERTICAL" },
		{ file = "Fury of Stormrage", id = 460831, orientation = "HORIZONTAL" },
		{ file = "Nature's Grace", id = 450929, orientation = "VERTICAL" },
		{ file = "Omen of Clarity", id = 510823, orientation = "VERTICAL" },
		{ file = "Predatory Swiftness", id = 898423, orientation = "HORIZONTAL" },
		{ file = "Predatory Swiftness Green", id = 1518303, orientation = "HORIZONTAL" },
		{ file = "Shooting Stars", id = 463452, orientation = "HORIZONTAL" },
		{ file = "Tooth and Claw", id = 774420, orientation = "VERTICAL" },
	},
	[ "Rogue" ] = {
		{ file = "Bandit's Guile", id = 1030393, orientation = "VERTICAL" },
		{ file = "Slice and Dice", id = 450931, orientation = "HORIZONTAL" },
	},
	[ "Priest" ] = {
		{ file = "Serendipity", id = 469752, orientation = "HORIZONTAL" },
		{ file = "Shadow Word: Insanity", id = 656728, orientation = "VERTICAL" },
		{ file = "Surge of Darkness", id = 592058, orientation = "VERTICAL" },
		{ file = "Surge of Light", id = 450933, orientation = "VERTICAL" },
	},
	[ "Death Knight" ] = {
		{ file = "Blood Boil", id = 511104, orientation = "VERTICAL" },
		{ file = "Dark Transformation", id = 461878, orientation = "HORIZONTAL" },
		{ file = "Killing Machine", id = 458740, orientation = "VERTICAL" },
		{ file = "Necropolis", id = 511105, orientation = "HORIZONTAL" },
		{ file = "Rime", id = 450930, orientation = "HORIZONTAL" },
		{ file = "Shadow of Death", id = 627609, orientation = "HORIZONTAL" },
		{ file = "Sudden Doom", id = 450932, orientation = "VERTICAL" },
	},
	[ "Warrior" ] = {
		{ file = "Blood Surge", id = 449487, orientation = "HORIZONTAL" },
		{ file = "Raging Blow", id = 962497, orientation = "VERTICAL" },
		{ file = "Sudden Death", id = 449493, orientation = "VERTICAL" },
		{ file = "Sword and Board", id = 449494, orientation = "VERTICAL" },
		{ file = "Ultimatum", id = 627610, orientation = "HORIZONTAL" },
	},
};